import * as litematica from '@cartographer/litematica';
import { BlockSpace } from '../../block-generation';

const MAP_SIZE = 128;

/**
 * Converts BlockSpace data into a litematica schema. The resulting schema data will need to be serialized
 * using the 'nbt' module before exporting
 */
export const generateLitematicaSchema = (block_space: BlockSpace) => {
  return litematica.generateSchematicNBT({
    blocks: block_space,
    name: 'Map',
    author: 'Cartographer',
    description: 'MapArt schematic generated by Cartographer'
  });
};

/**
 * Split a BlockSpace into individual 128×128 map tile litematica schemas.
 *
 * Returns a 2D array [tileZ][tileX] of litematica NBT objects, each representing
 * the blocks inside its 128×128 tile. Tiles with no blocks will have a null entry.
 */
export const generateSplitLitematicaSchemas = (
  block_space: BlockSpace,
  mapScaleX: number,
  mapScaleY: number
): (object | null)[][] => {
  // Group blocks by tile coordinates
  const tiles = new Map<string, BlockSpace>();
  for (const block of block_space) {
    const tileX = Math.floor(block.x / MAP_SIZE);
    const tileZ = Math.floor(block.z / MAP_SIZE);

    if (tileX < 0 || tileX >= mapScaleX || tileZ < 0 || tileZ >= mapScaleY) {
      continue;
    }

    const key = `${tileZ}:${tileX}`;
    if (!tiles.has(key)) {
      tiles.set(key, []);
    }
    // Shift coordinates to be local to the tile (origin at 0,0,0)
    tiles.get(key)!.push({
      ...block,
      x: block.x - tileX * MAP_SIZE,
      z: block.z - tileZ * MAP_SIZE
    });
  }

  // Build the 2D array [tileZ][tileX]
  const result: (object | null)[][] = [];
  for (let tileZ = 0; tileZ < mapScaleY; tileZ++) {
    const row: (object | null)[] = [];
    for (let tileX = 0; tileX < mapScaleX; tileX++) {
      const key = `${tileZ}:${tileX}`;
      const tileBlocks = tiles.get(key);
      if (tileBlocks && tileBlocks.length > 0) {
        row.push(
          litematica.generateSchematicNBT({
            blocks: tileBlocks,
            name: `Map_x${tileX}_z${tileZ}`,
            author: 'Cartographer',
            description: `MapArt tile at (${tileX}, ${tileZ}) generated by Cartographer`
          })
        );
      } else {
        row.push(null);
      }
    }
    result.push(row);
  }

  return result;
};
